spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:venda_api
    username: sa
    password:

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
